name: Docker Image CI

on:
  push:
    branches: none #[ "main" ]
  pull_request:
    branches: none #[ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: .
      run: docker build . --file Dockerfile --tag qbittorrent-filebot:$(date +%s)
